// Build the self-contained MCP server bundle for the plugin (P2.0).
//
// When a plugin is installed from a marketplace, Claude Code fetches only the
// plugin's source dir and runs its MCP server with NO `npm install`. So the
// server must be one self-contained file. esbuild bundles src/mcp/server.js +
// @hmh/core + the Claude adapter + zod + the MCP SDK, and inlines the two HTML
// templates as strings (the `.html` text loader), into:
//
//   plugins/hold-my-hand/dist/hmh-mcp.mjs   (committed — see .gitignore note)
//
// Run: `npm run build:plugin` (which also runs build-skill.mjs).

import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const outfile = path.join(root, 'plugins', 'hold-my-hand', 'dist', 'hmh-mcp.mjs');

await build({
  entryPoints: [path.join(root, 'src', 'mcp', 'server.js')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  // Inline the HTML templates as strings so the bundle needs no template files.
  loader: { '.html': 'text' },
  // Keep node built-ins external (they're always available at runtime).
  banner: {
    js: '// GENERATED by build.mjs — do not edit. Source: src/mcp/server.js + @hmh/core.\n'
      + "import { createRequire as __hmhCreateRequire } from 'node:module';\n"
      + 'const require = __hmhCreateRequire(import.meta.url);\n',
  },
  logLevel: 'info',
});

process.stderr.write(`✓ built ${path.relative(root, outfile)}\n`);
